spring:
  application:
    name: cloud-gateway
  cloud:
    gateway:
      routes:
      - id: hello-service
        uri: lb://hello-service
        predicates:
        - Path=/hello/**
        filters:
        - StripPrefix=1
      - id: ws-service
        uri: lb:ws://ws-service
        predicates:
        - Path=/ws/**
        filters:
        - StripPrefix=1
server:
  port: 10000
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/