eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/,http://localhost:8762/eureka/

server:
  port: 8861

spring:
  application:
    name: hello-service
  zipkin:
    base-url: http://localhost:9411
