server:
  port: 10000

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/

spring:
  application:
    name: gateway-spring

---
spring:
  cloud:
    gateway:
      routes:
      - id: limit_service-hello
        uri: lb://service-hello
        predicates:
        - Path=/hello/**
        filters:
        - StripPrefix=1
        - name: RequestRateLimiter
          args:
            key-resolver: '#{@hostAddrKeyResolver}'
            redis-rate-limiter.replenishRate: 1
            redis-rate-limiter.burstCapacity: 10
  redis:
    host: localhost
    port: 6379
    database: 0




